apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    run: zoo
  name: zoo
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/zoo
spec:
  replicas: 1
  selector:
    matchLabels:
      run: zoo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: zoo
    spec:
      containers:
      - image: zookeeper:latest
        imagePullPolicy: Always
        name: zoo
        ports:
        - containerPort: 2181
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
