apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: kafka
  name: kafka
  selfLink: /api/v1/namespaces/default/services/kafka
spec:
  ports:
  - port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    run: kafka
  sessionAffinity: None
  type: NodePort
