apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: zookeeper
  name: zookeeper
  selfLink: /api/v1/namespaces/default/services/zookeeper
spec:
  ports:
  - port: 2181
    protocol: TCP
    targetPort: 2181
  selector:
    run: zookeeper
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
