apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: jg-kafka
  name: jg-kafka
  selfLink: /api/v1/namespaces/default/services/jg-kafka
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30158
    port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    run: jg-kafka
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
